# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c42b04143f0d8778b14c2b830867a6eb9fa45aaeb36b83017c93091c1779e8e0512955f158fff0b5ba8957a2cd940305b3ba18a79355ecf1a8e446523f7c403

test:
  secret_key_base: 08388d58d134408c0b1f7d4dc41da9bffe1c114e64a28238468d697361bfc79e2586255c733d946e693fdbb01ad15b90c503d0903ac53fed512f37b1b524b65b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
